const Homeproduct=[
    {
        id:1,
        name:'product1',
        price:'26',
        image: 'image/p1.webp',
        cat:'',
        type:'new',
    },
    {
        id:2,
        name:'product2',
        price:'260',
        image: 'image/p2.webp',
        cat:'',
        type:'new',
    },
    {
        id:3,
        name:'product3',
        price:'76',
        image: 'image/p3.webp',
        cat:'',
        type:'new',
    },
    {
        id:4,
        name:'product4',
        price:'786',
        image: 'image/p4.webp',
        cat:'',
        type:'new',
    },
    {
        id:5,
        name:'product5',
        price:'669',
        image: 'image/p5.webp',
        cat:'',
        type:'top',
    },
    {
        id:6,
        name:'product6',
        price:'200',
        image: 'image/p6.webp',
        cat:'',
        type:'featured',
    },
    {
        id:7,
        name:'product7',
        price:'500',
        image: 'image/p7.webp',
        cat:'',
        type:'top',
    },
    {
        id:8,
        name:'product8',
        price:'100',
        image: 'image/p8.webp',
        cat:'',
        type:'new',
    },
    {
        id:9,
        name:'product9',
        price:'100',
        image: 'image/p9.jpg',
        cat:'',
        type:'featured',
    },
    {
        id:10,
        name:'product10',
        price:'100',
        image: 'image/p10.jpg',
        cat:'',
        type:'featured',
    },
]

export default Homeproduct;